# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b05921055b1102ef0786ea216ef220d0ea4b6437807cc6fb22b1dce7c46fe2bcfee8efbab26d8ef33e64de9598299e3884f75aea0891cb6fac132747f0aec7f3

test:
  secret_key_base: 280de47405ccd972a82a6e7c4f6063fb2aad15b044906eac5bce4df81fd68f6cf954da66c3a74083fcf035c27eb9c29b2c3d9ddbb10639a6ab6a5a77a74c0ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
